import React from "react";
import "./community.css";

const Community = ({ classes }) => (
    <div>
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
        Community here <br />
    </div>
);

export default Community;
